#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo " "
echo  "**-----commit-lint analyzing----*"
echo " "

npx --no -- commitlint --edit $1
echo " "
echo "*---commit-lint analysis of the commit structure completed---*"
echo " "
